# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
        filenames: captioncleaner/*.py
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
        filenames: captioncleaner/*.py
    -   id: check-case-conflict
    -   id: check-docstring-first
        filenames: captioncleaner/*.py

    -   id: check-shebang-scripts-are-executable
    -   id: detect-private-key
    # -   id: no-commit-to-branch
        # args: ['-b main']
    -   id: requirements-txt-fixer
